services:
  bentopdf:
    # simple mode - bentopdf/bentopdf-simple:latest
    # default mode - bentopdf/bentopdf:latest
    #image: bentopdf/bentopdf-simple:latest
    build: .
    container_name: bentopdf
    restart: unless-stopped
    ports:
      - '3002:80'
    environment:
      - VITE_DEFAULT_LANGUAGE=id
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '1'
